# Generated by Django 5.0 on 2025-01-20

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0001_initial"),
        ("netbox_ssl", "0002_certificate_sans_gin_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateAuthority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True, help_text="Name of the Certificate Authority")),
                ("type", models.CharField(default="public", max_length=20, help_text="Type of Certificate Authority")),
                ("description", models.TextField(blank=True, help_text="Description of the Certificate Authority")),
                (
                    "issuer_pattern",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        help_text="Pattern to match in certificate issuer field for auto-detection",
                    ),
                ),
                ("website_url", models.URLField(blank=True, help_text="CA website URL")),
                ("portal_url", models.URLField(blank=True, help_text="CA portal/management URL")),
                ("contact_email", models.EmailField(blank=True, max_length=254, help_text="Contact email for this CA")),
                ("is_approved", models.BooleanField(default=True, help_text="Whether this CA is approved for use")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "Certificate Authority",
                "verbose_name_plural": "Certificate Authorities",
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="issuing_ca",
            field=models.ForeignKey(
                blank=True,
                help_text="Certificate Authority that issued this certificate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="netbox_ssl.certificateauthority",
            ),
        ),
    ]
