"""
Add URL Certificate Import discovery fields + permission to Certificate (#106, PR 1).

Foundation for the URL Certificate Import feature: two additive scalar fields
(`discovered_via_url`, `last_seen_at`) recording where/when a certificate was
scraped via TLS handshake, and a new `run_urlimport` permission (inert until the
import view lands in PR 2). All operations are additive / metadata-only —
reversible, no data migration, no NOT NULL backfill. Generated by NetBox's own
``makemigrations`` (not hand-authored) so it passes the #118 ``--check`` gate.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssl", "0023_compliance_tags_and_field_reconciliation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-valid_to", "common_name"],
                "permissions": [
                    ("import_certificate", "Can import certificates from PEM/DER/PKCS7"),
                    ("renew_certificate", "Can perform certificate renewal"),
                    ("bulk_operations", "Can perform bulk certificate operations"),
                    ("run_urlimport", "Can run URL certificate import"),
                ],
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="discovered_via_url",
            field=models.CharField(blank=True, db_index=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="certificate",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
