"""
URL configuration for NetBox SSL plugin.
"""

from django.urls import path
from netbox.views.generic import ObjectChangeLogView, ObjectContactsView

from . import models, views
from .views.analytics import CertificateAnalyticsDashboardView
from .views.compliance_report import ComplianceReportView
from .views.topology import CertificateMapFragmentView, CertificateMapView

urlpatterns = [
    # Certificate URLs
    path(
        "certificates/",
        views.CertificateListView.as_view(),
        name="certificate_list",
    ),
    path(
        "certificates/add/",
        views.CertificateEditView.as_view(),
        name="certificate_add",
    ),
    path(
        "certificates/import/",
        views.CertificateImportView.as_view(),
        name="certificate_import",
    ),
    path(
        "certificates/renew/",
        views.CertificateRenewView.as_view(),
        name="certificate_renew",
    ),
    path(
        "certificates/bulk-import/",
        views.CertificateBulkDataImportView.as_view(),
        name="certificate_bulk_import",
    ),
    path(
        "certificates/url-import/",
        views.UrlImportView.as_view(),
        name="certificate_url_import",
    ),
    path(
        "certificates/edit/",
        views.CertificateBulkEditView.as_view(),
        name="certificate_bulk_edit",
    ),
    path(
        "certificates/delete/",
        views.CertificateBulkDeleteView.as_view(),
        name="certificate_bulk_delete",
    ),
    path(
        "certificates/<int:pk>/",
        views.CertificateView.as_view(),
        name="certificate",
    ),
    path(
        "certificates/<int:pk>/edit/",
        views.CertificateEditView.as_view(),
        name="certificate_edit",
    ),
    path(
        "certificates/<int:pk>/delete/",
        views.CertificateDeleteView.as_view(),
        name="certificate_delete",
    ),
    path(
        "certificates/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="certificate_changelog",
        kwargs={"model": models.Certificate},
    ),
    path(
        "certificates/<int:pk>/contacts/",
        ObjectContactsView.as_view(),
        name="certificate_contacts",
        kwargs={"model": models.Certificate},
    ),
    path(
        "certificates/<int:pk>/assign-targets/",
        views.CertificateAssignTargetsView.as_view(),
        name="certificate_assign_targets",
    ),
    # Analytics / Insights URLs
    path(
        "analytics/",
        CertificateAnalyticsDashboardView.as_view(),
        name="analytics_dashboard",
    ),
    path(
        "compliance-report/",
        ComplianceReportView.as_view(),
        name="compliance_report",
    ),
    path(
        "certificate-map/",
        CertificateMapView.as_view(),
        name="certificate_map",
    ),
    path(
        "certificate-map/fragment/",
        CertificateMapFragmentView.as_view(),
        name="certificate_map_fragment",
    ),
    # CertificateSigningRequest URLs
    path(
        "csrs/",
        views.CertificateSigningRequestListView.as_view(),
        name="certificatesigningrequest_list",
    ),
    path(
        "csrs/add/",
        views.CertificateSigningRequestEditView.as_view(),
        name="certificatesigningrequest_add",
    ),
    path(
        "csrs/import/",
        views.CSRImportView.as_view(),
        name="csr_import",
    ),
    path(
        "csrs/edit/",
        views.CertificateSigningRequestBulkEditView.as_view(),
        name="certificatesigningrequest_bulk_edit",
    ),
    path(
        "csrs/delete/",
        views.CertificateSigningRequestBulkDeleteView.as_view(),
        name="certificatesigningrequest_bulk_delete",
    ),
    path(
        "csrs/<int:pk>/",
        views.CertificateSigningRequestView.as_view(),
        name="certificatesigningrequest",
    ),
    path(
        "csrs/<int:pk>/edit/",
        views.CertificateSigningRequestEditView.as_view(),
        name="certificatesigningrequest_edit",
    ),
    path(
        "csrs/<int:pk>/delete/",
        views.CertificateSigningRequestDeleteView.as_view(),
        name="certificatesigningrequest_delete",
    ),
    path(
        "csrs/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="certificatesigningrequest_changelog",
        kwargs={"model": models.CertificateSigningRequest},
    ),
    # CertificateAuthority URLs
    path(
        "certificate-authorities/",
        views.CertificateAuthorityListView.as_view(),
        name="certificateauthority_list",
    ),
    path(
        "certificate-authorities/add/",
        views.CertificateAuthorityEditView.as_view(),
        name="certificateauthority_add",
    ),
    path(
        "certificate-authorities/edit/",
        views.CertificateAuthorityBulkEditView.as_view(),
        name="certificateauthority_bulk_edit",
    ),
    path(
        "certificate-authorities/delete/",
        views.CertificateAuthorityBulkDeleteView.as_view(),
        name="certificateauthority_bulk_delete",
    ),
    path(
        "certificate-authorities/<int:pk>/",
        views.CertificateAuthorityView.as_view(),
        name="certificateauthority",
    ),
    path(
        "certificate-authorities/<int:pk>/edit/",
        views.CertificateAuthorityEditView.as_view(),
        name="certificateauthority_edit",
    ),
    path(
        "certificate-authorities/<int:pk>/delete/",
        views.CertificateAuthorityDeleteView.as_view(),
        name="certificateauthority_delete",
    ),
    path(
        "certificate-authorities/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="certificateauthority_changelog",
        kwargs={"model": models.CertificateAuthority},
    ),
    # ExternalSource URLs
    path(
        "external-sources/",
        views.ExternalSourceListView.as_view(),
        name="externalsource_list",
    ),
    path(
        "external-sources/add/",
        views.ExternalSourceEditView.as_view(),
        name="externalsource_add",
    ),
    path(
        "external-sources/edit/",
        views.ExternalSourceBulkEditView.as_view(),
        name="externalsource_bulk_edit",
    ),
    path(
        "external-sources/delete/",
        views.ExternalSourceBulkDeleteView.as_view(),
        name="externalsource_bulk_delete",
    ),
    path(
        "external-sources/<int:pk>/",
        views.ExternalSourceView.as_view(),
        name="externalsource",
    ),
    path(
        "external-sources/<int:pk>/edit/",
        views.ExternalSourceEditView.as_view(),
        name="externalsource_edit",
    ),
    path(
        "external-sources/<int:pk>/delete/",
        views.ExternalSourceDeleteView.as_view(),
        name="externalsource_delete",
    ),
    path(
        "external-sources/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="externalsource_changelog",
        kwargs={"model": models.ExternalSource},
    ),
    # CompliancePolicy URLs
    path(
        "compliance-policies/",
        views.CompliancePolicyListView.as_view(),
        name="compliancepolicy_list",
    ),
    path(
        "compliance-policies/add/",
        views.CompliancePolicyEditView.as_view(),
        name="compliancepolicy_add",
    ),
    path(
        "compliance-policies/delete/",
        views.CompliancePolicyBulkDeleteView.as_view(),
        name="compliancepolicy_bulk_delete",
    ),
    path(
        "compliance-policies/<int:pk>/",
        views.CompliancePolicyView.as_view(),
        name="compliancepolicy",
    ),
    path(
        "compliance-policies/<int:pk>/edit/",
        views.CompliancePolicyEditView.as_view(),
        name="compliancepolicy_edit",
    ),
    path(
        "compliance-policies/<int:pk>/delete/",
        views.CompliancePolicyDeleteView.as_view(),
        name="compliancepolicy_delete",
    ),
    path(
        "compliance-policies/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="compliancepolicy_changelog",
        kwargs={"model": models.CompliancePolicy},
    ),
    # ComplianceCheck URLs
    path(
        "compliance-checks/",
        views.ComplianceCheckListView.as_view(),
        name="compliancecheck_list",
    ),
    path(
        "compliance-checks/delete/",
        views.ComplianceCheckBulkDeleteView.as_view(),
        name="compliancecheck_bulk_delete",
    ),
    path(
        "compliance-checks/<int:pk>/",
        views.ComplianceCheckView.as_view(),
        name="compliancecheck",
    ),
    path(
        "compliance-checks/<int:pk>/delete/",
        views.ComplianceCheckDeleteView.as_view(),
        name="compliancecheck_delete",
    ),
    path(
        "compliance-checks/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="compliancecheck_changelog",
        kwargs={"model": models.ComplianceCheck},
    ),
    # MonitoredEndpoint URLs
    path(
        "monitored-endpoints/",
        views.MonitoredEndpointListView.as_view(),
        name="monitoredendpoint_list",
    ),
    path(
        "monitored-endpoints/add/",
        views.MonitoredEndpointEditView.as_view(),
        name="monitoredendpoint_add",
    ),
    path(
        "monitored-endpoints/import/",
        views.MonitoredEndpointImportView.as_view(),
        name="monitoredendpoint_import",
    ),
    path(
        "monitored-endpoints/delete/",
        views.MonitoredEndpointBulkDeleteView.as_view(),
        name="monitoredendpoint_bulk_delete",
    ),
    path(
        "monitored-endpoints/<int:pk>/",
        views.MonitoredEndpointView.as_view(),
        name="monitoredendpoint",
    ),
    path(
        "monitored-endpoints/<int:pk>/edit/",
        views.MonitoredEndpointEditView.as_view(),
        name="monitoredendpoint_edit",
    ),
    path(
        "monitored-endpoints/<int:pk>/delete/",
        views.MonitoredEndpointDeleteView.as_view(),
        name="monitoredendpoint_delete",
    ),
    path(
        "monitored-endpoints/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="monitoredendpoint_changelog",
        kwargs={"model": models.MonitoredEndpoint},
    ),
    # CertificateAssignment URLs
    path(
        "assignments/",
        views.CertificateAssignmentListView.as_view(),
        name="certificateassignment_list",
    ),
    path(
        "assignments/add/",
        views.CertificateAssignmentEditView.as_view(),
        name="certificateassignment_add",
    ),
    path(
        "assignments/delete/",
        views.CertificateAssignmentBulkDeleteView.as_view(),
        name="certificateassignment_bulk_delete",
    ),
    path(
        "assignments/<int:pk>/",
        views.CertificateAssignmentView.as_view(),
        name="certificateassignment",
    ),
    path(
        "assignments/<int:pk>/edit/",
        views.CertificateAssignmentEditView.as_view(),
        name="certificateassignment_edit",
    ),
    path(
        "assignments/<int:pk>/delete/",
        views.CertificateAssignmentDeleteView.as_view(),
        name="certificateassignment_delete",
    ),
    path(
        "assignments/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="certificateassignment_changelog",
        kwargs={"model": models.CertificateAssignment},
    ),
]
