"""
Certificate Signing Request (CSR) model for tracking pending certificate requests.

This model stores imported CSR metadata for tracking purposes.
CSRs are not generated by this plugin - they are imported from external sources.
"""

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from netbox.models import NetBoxModel
from utilities.choices import ChoiceSet


class CSRStatusChoices(ChoiceSet):
    """Status choices for CSRs."""

    STATUS_PENDING = "pending"
    STATUS_APPROVED = "approved"
    STATUS_REJECTED = "rejected"
    STATUS_ISSUED = "issued"
    STATUS_EXPIRED = "expired"

    CHOICES = [
        (STATUS_PENDING, "Pending", "yellow"),
        (STATUS_APPROVED, "Approved", "green"),
        (STATUS_REJECTED, "Rejected", "red"),
        (STATUS_ISSUED, "Issued", "cyan"),
        (STATUS_EXPIRED, "Expired", "gray"),
    ]


class CertificateSigningRequest(NetBoxModel):
    """
    A Certificate Signing Request (CSR).

    This model stores CSR metadata imported from external sources.
    Private keys are never stored; CSRs contain only the public key.
    """

    # Subject information
    common_name = models.CharField(
        max_length=255,
        help_text="Common Name (CN) from the CSR subject",
    )
    organization = models.CharField(
        max_length=255,
        blank=True,
        help_text="Organization (O) from the CSR subject",
    )
    organizational_unit = models.CharField(
        max_length=255,
        blank=True,
        help_text="Organizational Unit (OU) from the CSR subject",
    )
    locality = models.CharField(
        max_length=255,
        blank=True,
        help_text="Locality/City (L) from the CSR subject",
    )
    state = models.CharField(
        max_length=255,
        blank=True,
        help_text="State/Province (ST) from the CSR subject",
    )
    country = models.CharField(
        max_length=2,
        blank=True,
        help_text="Country (C) from the CSR subject (2-letter code)",
    )

    # Subject Alternative Names
    sans = ArrayField(
        models.CharField(max_length=255),
        blank=True,
        default=list,
        help_text="Requested Subject Alternative Names (DNS names, IPs, etc.)",
    )

    # Key information
    key_size = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Key size in bits (e.g., 2048, 4096)",
    )
    algorithm = models.CharField(
        max_length=20,
        help_text="Key algorithm (RSA, ECDSA, Ed25519)",
    )

    # CSR data
    fingerprint_sha256 = models.CharField(
        max_length=95,  # SHA256 with colons: 64 hex + 31 colons
        unique=True,
        help_text="SHA256 fingerprint of the CSR",
    )
    pem_content = models.TextField(
        help_text="CSR in PEM format",
    )

    # Status tracking
    status = models.CharField(
        max_length=20,
        choices=CSRStatusChoices,
        default=CSRStatusChoices.STATUS_PENDING,
        help_text="Current status of the CSR",
    )

    # Tracking fields
    requested_date = models.DateTimeField(
        auto_now_add=True,
        help_text="When the CSR was imported/requested",
    )
    requested_by = models.CharField(
        max_length=255,
        blank=True,
        help_text="Who requested this certificate (person/team/system)",
    )
    target_ca = models.CharField(
        max_length=255,
        blank=True,
        help_text="Intended Certificate Authority for signing",
    )
    notes = models.TextField(
        blank=True,
        help_text="Additional notes about this CSR",
    )

    # Link to resulting certificate
    resulting_certificate = models.ForeignKey(
        "netbox_ssl.Certificate",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="source_csr",
        help_text="Certificate issued from this CSR",
    )

    # Multi-tenancy support
    tenant = models.ForeignKey(
        to="tenancy.Tenant",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="csrs",
        help_text="Tenant this CSR belongs to",
    )

    class Meta:
        ordering = ["-requested_date", "common_name"]
        verbose_name = "Certificate Signing Request"
        verbose_name_plural = "Certificate Signing Requests"

    def __str__(self):
        return f"{self.common_name} ({self.get_status_display()})"

    def get_absolute_url(self):
        return reverse("plugins:netbox_ssl:certificatesigningrequest", args=[self.pk])

    @property
    def subject_string(self):
        """Build a subject string from the CSR fields."""
        parts = []
        if self.common_name:
            parts.append(f"CN={self.common_name}")
        if self.organization:
            parts.append(f"O={self.organization}")
        if self.organizational_unit:
            parts.append(f"OU={self.organizational_unit}")
        if self.locality:
            parts.append(f"L={self.locality}")
        if self.state:
            parts.append(f"ST={self.state}")
        if self.country:
            parts.append(f"C={self.country}")
        return ", ".join(parts)

    def mark_issued(self, certificate):
        """Mark this CSR as issued and link to the certificate."""
        self.status = CSRStatusChoices.STATUS_ISSUED
        self.resulting_certificate = certificate
        self.save()
